### ISSUE TITLE
Cross Browser problems with checkboxes and radios.

### ISSUE THREAD

**Issue by iainhenderson** [cferdinandi/validate#31] opened 2017-09-25 08:35 UTC
Hi, there seem to be some problems with checkboxes and radios on [your demo page](https://cferdinandi.github.io/validate/)  These impact different browsers in different ways.

**Chrome 61 Mac - Radio buttons**
Selecting 'Yes' is valid, selecting 'No' is invalid

**Safari 11 Mac - Radio buttons**
'Yes' and 'No' are both invalid

**Firefox 55. - Radio buttons**
'Yes' and 'No' are both invalid

**Chrome 61 - Checkboxes**
Only "Wolverine" is valid

**Safari 11 - Checkboxes**
No options are valid

**Firefox 55 - Checkboxes**
No options are valid

**Comment by cferdinandi** [comment] 2017-09-29 11:09
Hmm... I'm seeing this too. I'll look into this, thanks!

**Comment by cferdinandi** [comment] 2018-03-14 15:14
Sorry for the lengthy delay in fixing this. It appears to have been causing by a polyfill conflict, and should be resolved with v1.1.3.

Looks like it may have been caused by a conflict with this: https://github.com/cferdinandi/validate/issues/27

**Closed as completed by cferdinandi** 2018-03-14 15:14 UTC
Labels: bug
